### PR TITLE
Update to use latest eclipse, tycho, java

### PR DESCRIPTION
**Pull request by gnl42**
Set defaults to:
Java: 17
Tycho: 3.0.1
Eclipse: latest

fixes .gitignore problem, blank lines in pom.xml

updates a bunch of maven plugins

### CODE REVIEW

**Comment by bmaggi** [comment]
Hi @gnl42 , 

Thanks for your PR. 

I tried it locally and it's failing on a **mvn clean install** 

Did you managed to run it on your computer ? 

```
[INFO] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[INFO] [ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0) @ 
[INFO]  @ 
[INFO] [ERROR] The build could not read 1 project -> [Help 1]
[INFO] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[INFO] [ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0) @ 
[INFO] 
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:397)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[INFO]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:566)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] [ERROR]   
[INFO] [ERROR]   The project myGroupId:myArtifactId:1.0.0-SNAPSHOT (C:\github\bmaggi\eclipse-tycho-archetype\target\test-classes\projects\java17-tycho3.0.1-latest\project\myArtifactId\pom.xml) has 1 error
[INFO] [ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0): No versions available for org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0) within specified range -> [Help 2]
[INFO] org.apache.maven.plugin.PluginManagerException: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:849)
[INFO]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)
[INFO]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)
[INFO]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1368)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:460)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[INFO]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:566)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:217)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)
[INFO]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)
[INFO]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)
[INFO]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1368)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:460)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[INFO]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:566)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.1 -> org.eclipse.tycho:tycho-core:jar:3.0.1 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.1 -> org.eclipse.platform:org.eclipse.equinox.p2.publisher:jar:1.7.200 -> org.eclipse.platform:org.eclipse.equinox.p2.artifact.repository:jar:1.4.600 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:291)
[INFO]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:205)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)
[INFO]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)
[INFO]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)
[INFO]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1368)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:460)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[INFO]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:566)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for org.eclipse.platform:org.eclipse.equinox.common:jar:[3.15.100,4.0.0) within specified range
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.filterVersions (DefaultDependencyCollector.java:654)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:397)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse (DefaultDependencyCollector.java:509)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:461)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency (DefaultDependencyCollector.java:365)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process (DefaultDependencyCollector.java:352)
[INFO]     at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:254)
[INFO]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:284)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:205)
[INFO]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:152)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)
[INFO]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)
[INFO]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)
[INFO]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)
[INFO]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1368)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:460)
[INFO]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[INFO]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[INFO]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[INFO]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:566)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] [ERROR] 
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[INFO] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
[INFO] Post-archetype-generation invoker exit code: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.998 s
[INFO] Finished at: 2023-02-09T18:55:18+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gnl42** [comment]
Hi,
  I installed it locally and used it to create a new project.

Any chance you have your environment set up to use an older eclipse repository?

Maybe try explicitly adding :
`    <repositories>
        <repository>
            <id>eclipse</id>
            <url>https://download.eclipse.org/releases/latest</url>
            <layout>p2</layout>
        </repository>
  </repositories>
` 
to the pom.xml

George

**Comment by bmaggi** [comment]
Hi,

So I managed to make (using github action) 
- the master branch running with Java 11 
- you branch running with Java 17 

The issue was with my local configuration witch is having some reference to outdated maven repositories 

I will mere this branch and make some more test locally (when I have the time) before releasing a new version

Thanks
Benoît

**Comment by bmaggi** [comment]
Hi,

I just released a new version 1.0.2 in Maven Central 

Works on my machine with 

```
mvn archetype:generate -DarchetypeGroupId=com.github.bmaggi -DarchetypeArtifactId=eclipse-tycho-archetype -DarchetypeVersion=1.0.2 -DgroupId=com -DartifactId=acme
```

Regards,
Benoît

**Pull request merged**
